#
# Module manifest for module 'VsDevCmd'
# Generated by: Eric
# Generated on: 1/7/2020
#

@{
	# RootModule = ''               # Script module or binary module file associated with this manifest.
	ModuleToProcess       = 'VisualStudioShell.psm1'
	ModuleVersion         = '0.1.0'
	GUID                  = '5ca15b3d-9366-45d7-b366-2a9c1d2bcd25'
	Author                = 'Eric'
	CompanyName           = 'Eric'
	Copyright             = '(c) 2019-2020 Eric. All rights reserved.'
	Description           = 'Starts Visual Studio or Developer Command Prompt'
	PowerShellVersion     = '2.0'   # Minimum version of the PowerShell engine required
	# CompatiblePSEditions = @()    # Supported PSEditions
	# PowerShellHostName = ''       # Name of the PowerShell host required
	# PowerShellHostVersion = ''    # Minimum version of the PowerShell host required
	# DotNetFrameworkVersion = ''   # Minimum version of Microsoft .NET Framework required (PowerShell Desktop)
	CLRVersion            = '2.0'   # Minimum version of the CLR required (PowerShell Desktop)
	ProcessorArchitecture = 'None'  # Processor architecture (None, X86, Amd64) required
	# RequiredModules = @()         # Modules that must be imported prior to this module
	# RequiredAssemblies = @()      # Assemblies that must be loaded prior to this module

	ScriptsToProcess      = @()     # Script files (.ps1) run in the caller's environment prior to importing this module.
	TypesToProcess        = @()     # Type files (.ps1xml) to be loaded when importing this module
	FormatsToProcess      = @()     # Format files (.ps1xml) to be loaded when importing this module
	NestedModules         = @()     # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
	FunctionsToExport     = @(      # Functions to export
		"Confirm-VisualStudioInstance"
		"Confirm-WindowsSdkVersion"
		"Enter-VisualStudioShell"
		"Format-VisualStudioShellArguments"
		"Get-VisualStudio"
		"Import-VisualStudioShellModule"
		"Import-VisualStudioSetupModule"
		"Start-VisualStudio"
	)
	CmdletsToExport       = @()     # Cmdlets to export
	VariablesToExport     = '*'     # Variables to export
	AliasesToExport       = @(      # Aliases to export from this module
		"vshell"
		"vs"
	)
	DscResourcesToExport  = @()     # DSC resources to export from this module
	ModuleList            = @()     # List of all modules packaged with this module
	FileList              = @()     # List of all files packaged with this module

	# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
	PrivateData           = @{

		PSData = @{

			# Tags applied to this module. These help with module discovery in online galleries.
			# Tags = @()

			# A URL to the license for this module.
			# LicenseUri = ''

			# A URL to the main website for this project.
			# ProjectUri = ''

			# A URL to an icon representing this module.
			# IconUri = ''

			# ReleaseNotes of this module
			# ReleaseNotes = ''

			# Prerelease string of this module
			# Prerelease = ''

			# Flag to indicate whether the module requires explicit user acceptance for install/update/save
			RequireLicenseAcceptance = $true

			# External dependent modules of this module
			# ExternalModuleDependencies = @()

		} # End of PSData hashtable

	} # End of PrivateData hashtable

	# HelpInfo URI of this module
	# HelpInfoURI = ''

	# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
	# DefaultCommandPrefix = ''
}

